name: Scrape And Save News

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # هر ساعت یکبار اجرا می‌شود

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper script
        run: python Scraper.py

      # این مرحله بسیار مهم است
      # تغییرات فایل sent_links.txt را به مخزن کامیت می‌کند
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update sent news links"
          file_pattern: sent_links.txt
